Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -32,3 +32,50 @@ jobs:
 
       - name: Run Selenium Cucumber Tests in Docker
         run: docker run --rm selenium-tests
+
+      - name: Generate Allure Report
+        run: |
+          npm install -g allure-commandline
+          allure generate allure-results --clean -o test-results/allure-report || echo "Allure report generation failed."
+          ls -la test-results/allure-report 
+          # mkdir -p allure-report/history
+          # if [ -d allure-report ]; then cp -r allure-report/history test-results/allure-results/; fi
+          # npm install -g allure-commandline
+          # allure generate allure-results --clean -o allure-report
+
+         
+      - name: Upload Allure Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report
+          path: test-results/allure-report 
+
+      - name: Debug Playwright Report
+        run: ls -la test-results/playwright-report || echo "No Playwright report found"
+
+      - name: Upload Playwright Test Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: playwright-html-report
+          path: playwright-report/
+          if-no-files-found: ignore  # ✅ Ignore missing files instead of showing warnings
+
+      - name: Deploy Allure Report to GitHub Pages
+        if: success()
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          personal_token: ${{ secrets.GH_PAT }}
+          publish_branch: gh-pages
+          publish_dir: test-results/allure-report 
+          destination_dir: allure-report
+          keep_files: false
+          
+      - name: Deploy Playwright HTML Report to GitHub Pages
+        if: success()
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          personal_token: ${{ secrets.GH_PAT }}
+          publish_branch: gh-pages
+          publish_dir: playwright-report/
+          destination_dir: playwright-report
+          keep_files: false
